# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Apuntes de Algoritmos y Programación II
author: Cátedra de Algoritmos y Programación II
copyright: "2025"
logo: assets/images/untref-logo.svg
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: true
  stderr_output: show
  nb_merge_streams: true

parse:
  myst_enable_extensions:
    - amsmath
    - attrs_inline
    - attrs_block
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

html:
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  comments:
    hypothesis: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: apunte.tex

repository:
  url: https://github.com/untref-ayp2/apuntes
  path_to_book: contenidos
  branch: main

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_proof
    - bokeh.sphinxext.bokeh_plot
  config:
    language: es
    bibtex_reference_style: author_year
    proof_minimal_theme: true
    html_static_path:
      - _static
    rst_epilog: |
      .. role:: red
         :class: red-text
      .. role:: blue
         :class: blue-text
      .. role:: green
         :class: green-text
