# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Apuntes de Estructuras de Datos
author: Cátedra de Estructuras de Datos
copyright: "2025"
logo: assets/images/untref-logo.svg
only_build_toc_files: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: auto
  allow_errors: true
  stderr_output: show
  nb_merge_streams: true

launch_buttons:
  thebe: true

parse:
  myst_enable_extensions:
    - amsmath
    - attrs_inline
    - attrs_block
    - colon_fence
    - deflist
    - dollarmath
    - fieldlist
    - html_admonition
    - html_image
    - linkify
    - replacements
    - smartquotes
    - strikethrough
    - substitution
    - tasklist

html:
  use_edit_page_button: false
  use_repository_button: true
  use_issues_button: true

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: apunte.tex

repository:
  url: https://github.com/untref-edd/apuntes
  path_to_book: contenidos
  branch: main

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

sphinx:
  extra_extensions:
    - sphinx_proof
    - sphinx_thebe
    - bokeh.sphinxext.bokeh_plot
    - sphinxcontrib.bibtex
    - sphinxcontrib.mermaid
  config:
    language: es
    bibtex_bibfiles:
      - references.bib
    bibtex_default_style: plain
    bibtex_reference_style: author_year
    proof_minimal_theme: true
    html_static_path:
      - _static
    html_css_files:
      - css/rtd_custom.css
    html_theme: sphinx_rtd_theme
    html_theme_options:
      logo_only: true
      collapse_navigation: false
    rst_epilog: |
      .. role:: red
         :class: red-text
      .. role:: blue
         :class: blue-text
      .. role:: green
         :class: green-text
